# Generated by Django 3.2.3 on 2021-05-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('new_date', models.DateTimeField()),
                ('pub_date', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='mediaForm/')),
            ],
        ),
    ]
